#!/bin/bash

# Definizione delle variabili
DOWNLOAD_DIR="$HOME/"
CROMITE_DIR="$HOME/Cromite"
FILE_URL="https://github.com/uazo/cromite/releases/latest/download/chrome-lin64.tar.gz"
FILE_NAME="chrome-lin64.tar.gz"
ICON_URL="https://camo.githubusercontent.com/6b4ee03be91712db2d81b603a1bb83553e97b66fa49443bf27b641089ea51696/68747470733a2f2f7777772e63726f6d6974652e6f72672f6170705f69636f6e2e706e67"
ICON_NAME_PATH="$HOME/Cromite/cromite_icon.png"
ICON_DEST1="/usr/share/icons/hicolor/192x192/apps/cromite.png"
ICON_DEST2="/usr/share/icons/hicolor/192x192/apps/cromite"
CROMUP_URL="https://raw.githubusercontent.com/RootGPT-YouTube/rootgpt-Cromup/refs/heads/main/cromup"
CROMUP_PATH="/url/local/bin/cromup"
CROMUP_DIR="$HOME/Cromite/cromup"

# Installazione di pv (se non presente)
echo -e "\e[1;32mVerifica e installazione delle dipendenze: software pv...\e[0m"
if ! command -v pv &> /dev/null; then
    echo -e "\e[1;32mpv non trovato, installazione in corso...\e[0m"
    if command -v dnf &> /dev/null; then
        sudo dnf install pv -y
    elif command -v apt &> /dev/null; then
        sudo apt install pv -y
    elif command -v pacman &> /dev/null; then
        sudo pacman -S --noconfirm pv
    elif command -v zypper &> /dev/null; then
        sudo zypper install pv -y
    else
        echo -e "\e[1;32mImpossibile installare pv automaticamente. Installalo manualmente.\e[0m"
        exit 1
    fi
fi

# Scarica il file
echo -e "\e[1;32mDownload del file archivio di Cromite...\e[0m"
mkdir -p "$DOWNLOAD_DIR"
wget -O "$DOWNLOAD_DIR/$FILE_NAME" "$FILE_URL" || { echo -e "\e[1;32mErrore nel download di Cromite!\e[0m"; exit 1; }

# Crea la directory di destinazione se non esiste
mkdir -p "$CROMITE_DIR"

# Elimina i file .manifest nelle sottocartelle di Cromite
echo -e "\e[1;32mPulizia dei files .manifest delle vecchie versioni...\e[0m"
find "$CROMITE_DIR" -type f -name "*.manifest" -exec rm -f {} +

# Copia nuova icona
wget -O "$ICON_NAME_PATH" "$ICON_URL" || { echo -e "\e[1;32mErrore nel download dell'icona!\e[0m"; exit 1; }
sudo cp "$ICON_NAME_PATH" "$ICON_DEST1"
sudo cp "$ICON_NAME_PATH" "$ICON_DEST2"

# Estrazione con barra di avanzamento tramite pv
echo -e "\e[1;32mEstrazione del file archivio di Cromite...\e[0m"
pv -p -e -L 20000000 -s "$(stat -c%s "$DOWNLOAD_DIR/$FILE_NAME")" "$DOWNLOAD_DIR/$FILE_NAME" | tar -xz -f - -C "$CROMITE_DIR" --overwrite || { echo -e "\e[1;32mErrore nell'estrazione!\e[0m"; exit 1; }

# Sposta i file e cartelle e pulizia files ridondanti
echo -e "\e[1;32mInstallazione dei nuovi files di Cromite e pulizia dei files ridondanti...\e[0m"
cp -r "$CROMITE_DIR/chrome-lin/"* "$CROMITE_DIR/"
rm -rf "$CROMITE_DIR/chrome-lin"
rm "$DOWNLOAD_DIR/$FILE_NAME"
cp "$CROMITE_DIR/chrome" "$CROMITE_DIR/cromite"
rm "$CROMITE_DIR/chrome"

# Aggiornamento cromup
echo -e "\e[1;32mVerifica aggiornamenti cromup online...\e[0m"
wget -O "$CROMUP_DIR" "$CROMUP_URL"
sudo cp "$CROMUP_DIR" "$CROMUP_PATH"
sudo chmod a+x "$CROMUP_PATH"

# Fine script
echo -e "\e[1;32mCromite Browser installato con successso!\e[0m"
