#!/bin/bash

# == Variabili ==
CROMUP_URL="https://raw.githubusercontent.com/RootGPT-YouTube/rootgpt-Cromup/refs/heads/main/cromup"
CROMUP_PATH="/usr/local/bin/cromup"
CROMUP_DIR="$HOME/Cromite/cromup"

# == Aggiornamento cromup ==
echo -e "\e[1;32mVerifica aggiornamenti cromup online...\e[0m"
sleep 3
# wget -O "$CROMUP_DIR" "$CROMUP_URL"
curl -fL --progress-bar -o "$CROMUP_DIR" "$CROMUP_URL" || { echo -e "\e[1;32mErrore nel download dell'aggiornamento di cromup!\e[0m"; exit 1; }
sudo cp "$CROMUP_DIR" "$CROMUP_PATH"
sudo chmod a+x "$CROMUP_PATH"

# == Fine script ==
echo -e "\e[1;32mVerifica finale...\e[0m"
sleep 3
echo -e "\e[1;32mTutto ok!\e[0m"
sleep 3
